### ISSUE TITLE
How about adding this library / -ies to VCPKG

### ISSUE THREAD

**Issue by VolkerEnderlein** [coin3d/coin#160]
**[Original report](https://bitbucket.org/Coin3D/coin/issue/160) by Anonymous.**

----------------------------------------

Hi,

I used Coin3d since many years and payed for a commercial license in former times.

I'm still satisfied with the performance and functionality. So I was sad when seeing no progress for some time after it got moved to bitbucket.

I recently saw new commits and some about making it compile with cmake.

Did you think about adding this library to [vcpkg](https://github.com/Microsoft/vcpkg).
If you look into it's ports you will see an impressive listing of public domain software.
You can find: OGRE, VTK, ...
So Coin3D might be in good neibourhood ...

And while I only used and tested vcpkg under Windows with VS2017 it looks like linux and macOS are supported, too.

Maybe this would focus some people to this nice library into this nice library.

**Comment by luzpaz** [comment]
Check out https://github.com/microsoft/vcpkg/pull/9880

**Comment by VolkerEnderlein** [comment]
I am closing this issue as vcpkg now supports Coin, SoQt and simage. Thanks @rickertm for the fantastic work.
