### ISSUE TITLE
Tracking coin3d package versions on downstream distros

### ISSUE THREAD

**Issue by VolkerEnderlein** [coin3d/coin#164]
**[Original report](https://bitbucket.org/Coin3D/coin/issue/164) by luz paz (Bitbucket: [Chitty Cloud](https://bitbucket.org/Chitty Cloud), ).**

----------------------------------------

There is a very cool project called Repology. You can use it to track downstream integration of a package and see if distros are up to date with in this case coind3d. Perhaps this is something that could be added to the README ?
Here's an example:

[![Packaging status](https://repology.org/badge/vertical-allrepos/coin3.svg)](https://repology.org/metapackage/coin3/versions)[![Packaging status](https://repology.org/badge/vertical-allrepos/coin.svg)](https://repology.org/metapackage/coin/versions)[![Packaging status](https://repology.org/badge/vertical-allrepos/coin3d.svg)](https://repology.org/metapackage/coin3d/versions)

**Comment by ggabbiani** [comment]
Hi, 

I think that the badge for Coin4 package should be added as well

https://repology.org/project/coin4/versions

At least for Fedora and OpenMandriva the main version is added to Coin project name in order to install both versions if/when required.

Regards
Giampiero

**Comment by veelo** [comment]
Possibly the badge should be listed here as well: https://github.com/coin3d/coin/wiki

**Comment by VolkerEnderlein** [comment]
Done. I had to use some ugly HTML code in the wiki page to vertical align the images properly.
