### ISSUE TITLE
Migrate repositories to git version control system

### ISSUE THREAD

**Issue by VolkerEnderlein** [coin3d/coin#178]
**[Original report](https://bitbucket.org/Coin3D/coin/issue/178) by Volker Enderlein (Bitbucket: [VolkerEnderlein](https://bitbucket.org/VolkerEnderlein), GitHub: [VolkerEnderlein](https://github.com/VolkerEnderlein)).**

----------------------------------------

As Atlassian shuts down Mercurial support in not so far future \(see [https://bitbucket.org/blog/sunsetting-mercurial-support-in-bitbucket](https://bitbucket.org/blog/sunsetting-mercurial-support-in-bitbucket)\) we are forced to take a decision on whether we move away from BitBucket to a new home \(i.e., move over to a different Mercurial provider\) or migrate the repositories to git.

**Comment by TheHubbit** [comment]
Happy New Year! Thank you Volker and everyone who helped with the migration! I just cloned / built simage + coin. All complete with history, issues and docu - awesome job. Unfortunately I can't help with the tag / sub-repository questions either.
