### ISSUE TITLE
Create releases for Coin and all subsequent Gui Toolkits

### ISSUE THREAD

**Issue by VolkerEnderlein** [coin3d/coin#180]
**[Original report](https://bitbucket.org/Coin3D/coin/issue/180) by Volker Enderlein (Bitbucket: [VolkerEnderlein](https://bitbucket.org/VolkerEnderlein), GitHub: [VolkerEnderlein](https://github.com/VolkerEnderlein)).**

----------------------------------------

As the CMake stuff matures and the CI is in place and working we should force ourselves to make a release for Coin 4.0 and all the SoGui-Toolkits. Other repositories may release later \(I am thinking as of SimVoleon and Sc21\). This should be done before making the transition to Git/Github.

This issue should hold the necessary information and steps that need to be performed. 

First things that come to mind are the update on the documentation and repository structure. When talking about the repository structure I mean that we don’t need MSVC related parts of the build directory anymore as they can easily be generated with the CMake scripts. Documentation updates are needed for the INSTALL, README, …  files. Especially the build instructions need to be updated \(or at least synchronized with the Wiki pages\).

Feel free to add other related tasks.

**Comment by veelo** [comment]
Thank you for doing the releases, @VolkerEnderlein. Great job!

**Comment by VolkerEnderlein** [comment]
Thanks @veelo I just added the missing tar.gz sourceballs. One question remains: I simply copied the *.zip files from the Bitbucket server to preserve the SHA/MD5 check sums. But the zipfiles still contain Mercurial version control information. What do you think, should I remove the version control information and therefore change the SHA/MD5 check sums as the consumers need to update the path to the sources anyway or just keep it as it is?

**Comment by veelo** [comment]
My opinion is of little relevance, I think packagers may have a better answer. But I'd not expect any version control information in a zip archive. If I understand correctly: the version stays the same because the source code has not changed, yet if github generates the archives instead of bitbucket the check sums change, which may confuse distributions. I would not worry about that too much, and probably go with whatever was easiest for me...

**Comment by rickertm** [comment]
Is there any chance of a new patch release tag for Coin, simage, SoQt etc. given the many important changes in the past few weeks? This would definitely help in packaging, as some distributions or package managers only accept tagged versions without custom patches.

See also https://github.com/coin3d/soqt/issues/54

**Comment by VolkerEnderlein** [comment]
Sure we could do, now that the CI is fully functional again. But I would like to get a solution for issue #379 into this version. This is really a blocker for some of us. What version number would you suggest for Coin? 4.1.0 or 4.0.1? If we consider it a patch release I would vote for a 4.0.1.

**Comment by rickertm** [comment]
An update of the patch version, i.e., Coin 4.0.1, simage 1.8.1, SoQt 1.6.1 etc. would be fine for me. The new source archives with all submodules integrated also help a lot.

**Comment by rickertm** [comment]
Now that the issue has been closed it seems like a good time for new version tags? If there are further issues, these can always be resolved in a later patch release.
