### ISSUE TITLE
Spelling error in sources

### ISSUE THREAD

**Issue by lepalom** [coin3d/coin#363]
I have updated the Debian coin3 package and one of the tests have showed some small spell errors:

I: libcoin80c: spelling-error-in-binary usr/lib/x86_64-linux-gnu/libCoin.so.4.0.0 convertion conversion
I: libcoin80c: spelling-error-in-binary usr/lib/x86_64-linux-gnu/libCoin.so.4.0.0 fragement fragment
I: libcoin80c: spelling-error-in-binary usr/lib/x86_64-linux-gnu/libCoin.so.4.0.0 statment statement
I: libcoin80c: spelling-error-in-binary usr/lib/x86_64-linux-gnu/libCoin.so.4.0.0 touple tuple

Makeing a grep in the sources they appears in:

- src/misc/SoJavaScriptEngine.cpp:                                  "convertion of '%s' to SoField type '%s' failed",
- src/hardcopy/VectorizePSAction.cpp:  "% the gouraudtriangle PostScript fragement below is free",
- data/shaders/lights/SpotLight.glsl:  // need to read this variable outside the if statment to work around ATi driver issues
- data/shaders/lights/SpotLight.glsl:  // need to read this variable outside the if statment to work around ATi driver issues
- src/misc/SoShaderGenerator.cpp:  Add a statment to the main function.
- src/scxml/ScXMLEventTarget.cpp:                         "type/name/session touple already registered for this target");
- src/scxml/ScXMLEventTarget.cpp:                         "type/name/session touple already registered for another target");

Please, could you fix it?

**Comment by veelo** [comment]
Thanks for reporting this. Fixed.

I know there are many violations of [subject-verb agreement](https://webapps.towson.edu/ows/sub-verb.htm) in the documentation, a common grammatical error among Norwegians. So common, actually, that I was contacted many years ago by a retired Norwegian teacher of the English language who commented on my personal website, trying to point out what he thought were errors. He had been teaching it wrong all this time :-(
