### ISSUE TITLE
cpack: Package number defaults to 1 after git migration

### ISSUE THREAD

**Issue by TheHubbit** [coin3d/coin#365]
The function hg_info() in cpack.d/CMakeLists.txt needs to be ported as Mercurial is no longer used.

```
CMake Warning at cpack.d/CMakeLists.txt:113 (message):
  Mercurial not found, PACKAGE_BUILD_NUMBER set to 1
```

**Comment by ggabbiani** [comment]
Hi Thomas,

the commit efe55a29f068bfaf96da6c1e87712f2d4ec75c0b should have fixed the issue: could you try now?

Regards
Giampiero

**Comment by VolkerEnderlein** [comment]
I am closing this issue for now as it has been properly resolved. If some problems still remain feel free to reopen it or open a new issue.
