### ISSUE TITLE
cpack.d should not be blindly included

### ISSUE THREAD

**Issue by hobbes1069** [coin3d/coin#367]
As cpack.d is a submodule it should not be blindly included in CMakeLists.txt. It is not needed for distribution packaging on linux and added unnecessary complexity to the packaging process.

It could be wrapped in some sort of "if exists" conditional or only enabled if specifically requested.

**Comment by veelo** [comment]
See also https://github.com/coin3d/soqt/issues/54#issuecomment-574147852.

**Comment by veelo** [comment]
@ggabbiani as I think cpack is your baby, can we assign this to you?

**Comment by ggabbiani** [comment]
ok, I'll take it.

**Comment by ggabbiani** [comment]
Thanks Richard for your comment.  

As you can see from the old commit [removed legacy package generator](https://github.com/coin3d/coin/commit/a2a96a84c1335c5f4df5a89aa60b4e6b2da9b08f) actually cpack.d moved and isolated in a separate subproject the already existing CMake code from the entire Coin3D collection (ten projects roughly).  

But you are right, at the end it should be included only as an optional feature.

I've already approved the two proposed PRs [simage#31](https://github.com/coin3d/simage/pull/31#event-2947136683) and [soqt#55](https://github.com/coin3d/soqt/pull/55#event-2947135064). 

I'll bring the same changes in the rest of the projects.

Regards
Giampiero

**Comment by ggabbiani** [comment]
I completed the changes on the following component libs:

coin
ivtools
quarter
simvoleon
smallchange
soqt
sowin
soxt

@hobbes1069 - may I close the issue?

Many thanks
Giampiero

**Comment by hobbes1069** [comment]
I wouldn't mind seeing a link to the commit (for historical purposes if other find this) but yes.

**Comment by veelo** [comment]
https://github.com/coin3d/coin/commit/be8e3d57aeb5b4df6abb52c5fa88666d48e7d7a0
https://github.com/coin3d/ivtools/commit/e25ef1dd275e82d195c007ca0327569cdb845c62
https://github.com/coin3d/quarter/commit/3d38c20a51a4a2bce81cbb272b0cbc8145932376
https://github.com/coin3d/simvoleon/commit/2935173fb6027cf595e40a4bbb39b4ce5d7a5996
https://github.com/coin3d/smallchange/commit/0b445e4fdd94016d666ce57d6fe433af086ae557
https://github.com/coin3d/soqt/pull/55
https://github.com/coin3d/sowin/commit/3c2540e93c5e65e010aa1eb961cae9dd42d006b7
https://github.com/coin3d/soxt/commit/51835597d3ce9d4ee61a9a551da95a1a4019c93f
https://github.com/coin3d/simage/pull/31

Thank you.
