### ISSUE TITLE
coin.SoNurbsCurve windows: bad tesselation

### ISSUE THREAD

**Issue by looooo** [coin3d/coin#375]
Creating a SoNurbsCurve seems to always have a bad tesselation on windows. The SoComplexity node doesn't have any influence.

tested with pivy:
```python
from pivy import coin
import sys

from PySide2.QtWidgets import QApplication
from pivy.quarter import QuarterWidget

def main():

    root = coin.SoSeparator()
    draw_style = coin.SoDrawStyle()
    draw_style.lineWidth = 2
    complexity = coin.SoComplexity()
    complexity.value = 1.
    knot_vector = 5 * [0] + [0.2, 0.4, 0.6, 0.8] + 5 * [1]
    curve = coin.SoNurbsCurve()
    curve.knotVector.setValues(0, len(knot_vector), knot_vector)
    curve.numControlPoints = 9
    poles = coin.SoCoordinate4()
    poles.point.setValues(0, 9, [[1., 1., 0., 1.],
                                 [1., 0., 0., 1.],
                                 [1., 1., 0., 1.],
                                 [2., 1., 0., 1.],
                                 [2., 0., 0., 1.],
                                 [3., 0., 0., 1.],
                                 [3., 1., 0., 1.],
                                 [4., 1., 0., 1.],
                                 [4., 0., 0., 1.]])
    

    root += coin.SoCone()
    root += [poles, draw_style, curve]


    app = QApplication(sys.argv)
    viewer = QuarterWidget()
    viewer.setSceneGraph(root)
    viewer.setWindowTitle("minimal")
    viewer.show()
    sys.exit(app.exec_())

if __name__ == '__main__':
    main()


```
![bspline](https://user-images.githubusercontent.com/5084704/76297769-b0ec4480-62b8-11ea-8bf9-18c612008c8b.PNG)

**Comment by veelo** [comment]
You need SuperGLU. https://github.com/coin3d/superglu

**Comment by looooo** [comment]
thanks. Is this a replacement for libglu? Should I use superglu or libglu for linux?

**Comment by veelo** [comment]
Oh, I understood you were on Windows. On Linux this should work with the system provided GLU. Can you clarify?

**Comment by looooo** [comment]
Yes I tested on windows, but I wondered if it makes sense to build superglu also for linux / osx.

**Comment by veelo** [comment]
No, this only makes sense on Windows. Blame Microsoft for not staying up to date (for decades)...

**Comment by veelo** [comment]
I am not sure, but you may be able to find binaries under "Assets" on https://github.com/coin3d/superglu/releases.

**Comment by VolkerEnderlein** [comment]
Creating a SoNurbsCurve seems to always have a bad tesselation on
    windows. The SoComplexity node doesn't have any influence.
    
      tested with pivy:
      
        from pivy import coin
import sys

from PySide2.QtWidgets import QApplication
from pivy.quarter import QuarterWidget

def main():

    root = coin.SoSeparator()
    draw_style = coin.SoDrawStyle()
    draw_style.lineWidth = 2
    complexity = coin.SoComplexity()
    complexity.value = 1.
    knot_vector = 5 * [0] + [0.2, 0.4, 0.6, 0.8] + 5 * [1]
    curve = coin.SoNurbsCurve()
    curve.knotVector.setValues(0, len(knot_vector), knot_vector)
    curve.numControlPoints = 9
    poles = coin.SoCoordinate4()
    poles.point.setValues(0, 9, [[1., 1., 0., 1.],
                                 [1., 0., 0., 1.],
                                 [1., 1., 0., 1.],
                                 [2., 1., 0., 1.],
                                 [2., 0., 0., 1.],
                                 [3., 0., 0., 1.],
                                 [3., 1., 0., 1.],
                                 [4., 1., 0., 1.],
                                 [4., 0., 0., 1.]])
    

    root += coin.SoCone()
    root += [poles, draw_style, curve]


    app = QApplication(sys.argv)
    viewer = QuarterWidget()
    viewer.setSceneGraph(root)
    viewer.setWindowTitle("minimal")
    viewer.show()
    sys.exit(app.exec_())

if __name__ == '__main__':
    main()


      
      
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/coin3d/coin/issues/375?email_source=notifications\u0026email_token=ALFAIH57L677TR72CPTSVB3RGYA47A5CNFSM4LE2NLCKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IT2JGEA",
"url": "https://github.com/coin3d/coin/issues/375?email_source=notifications\u0026email_token=ALFAIH57L677TR72CPTSVB3RGYA47A5CNFSM4LE2NLCKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IT2JGEA",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
    
    As Windows does not provide out of the box support for GLU 1.3
      you need to link your Coin against superGLU. This can be easily
      done building superGLU before Coin and adding -DUSE_SUPERGLU=ON to
      the CMake command line on Windows.

**Comment by looooo** [comment]
Thanks for the hints. I am going to build the library as a own package for conda-forge and afterwards rebuild coin. I think this is the easiest way for conda.

There is no license given for superglu. Would it be possible to add one?

**Comment by VolkerEnderlein** [comment]
Sure, will do that tonight. The source is licensed under "SGI Free 
Software License B, Version 1.1"

**Comment by looooo** [comment]
thanks, I encountered one build issue:
https://github.com/coin3d/superglu/issues/10

Using superglue works fine:
![bspline](https://user-images.githubusercontent.com/5084704/76310072-61b10e80-62ce-11ea-856d-7e3f575cdcc9.PNG)

**Comment by VolkerEnderlein** [comment]
I just added a note about superglu to the [BuildWithCMake](https://github.com/coin3d/coin/wiki/BuildWithCMake) page.

**Comment by xiaomx32** [comment]
> thanks, I encountered one build issue: [coin3d/superglu#10](https://github.com/coin3d/superglu/issues/10)
> 
> Using superglue works fine: ![bspline](https://user-images.githubusercontent.com/5084704/76310072-61b10e80-62ce-11ea-856d-7e3f575cdcc9.PNG)

Hello, I use Coin, C++ and visual. When I draw the curve,  find that there are only straight lines, just as in your two diagrams.The code I wrote was to draw a heart curve. How do you link Coin and Superglue together.
![heart](https://user-images.githubusercontent.com/78308270/151162877-1cb9b328-8e0d-4e3b-8bf5-6d90c3abf03e.png)

**Comment by VolkerEnderlein** [comment]
@xiaomx32 Coin needs to be built with the superGLU lib. You need to build and locally install superGLU following the [build instructions](https://github.com/coin3d/coin/wiki/BuildWithCMake#windows). Otherwise, if you just want to try out if it works, you could also download the appropriate precompiled package from the [CI-builds](https://github.com/coin3d/coin/releases/tag/CI-builds) section. msvc15 = Visual Studio 15 2017, msvc16 = Visual Studio 16 2019. This should work out of the box.

**Comment by xiaomx32** [comment]
Thank you very much for your patient reply.  To tell you the truth, I am not familiar with cmake and "link" or other operations.  My Coin3d environment was built by watching online tutorials, and the tools I used were compiled and downloaded from Github.  In other words, although what you said is very clear, I still need time to understand.  
Please allow me to show you how my curves are coming along later.  Thanks again.

**Comment by VolkerEnderlein** [comment]
Are you sure the correct DLL is loaded? Maybe you are still loading an older DLL. I use [All Dlls Dependencies](http://jacquelin.potier.free.fr/AllDllDeps/) from Jacquelin Potier to check this. Another thing that comes to mind: Does your platform setting x86 / x64 is correct?

**Comment by xiaomx32** [comment]
Hi, to be honest, I'm not sure if I've got it right. If possible, I would like to send you some screenshots for you to check. I also use x86.

**Comment by VolkerEnderlein** [comment]
Can you add your data for the NurbsCurve example here? I will examine what's going on then.

**Comment by xiaomx32** [comment]
The example in this book, "The Inventor Mentor".
environment: Win10, visual 2019...
```c++
#include <Inventor/Win/SoWin.h>
#include <Inventor/Win/viewers/SoWinExaminerViewer.h>
#include <Inventor/nodes/SoBaseColor.h>
#include <Inventor/nodes/SoComplexity.h>
#include <Inventor/nodes/SoCoordinate3.h>
#include <Inventor/nodes/SoDrawStyle.h>
#include <Inventor/nodes/SoLightModel.h>
#include <Inventor/nodes/SoNurbsCurve.h>
#include <Inventor/nodes/SoPointSet.h>
#include <Inventor/nodes/SoSeparator.h>
#include <superglu.h>

float pts[7][3] = {
	{ 4.0, -6.0,  6.0},
	{-4.0,  1.0,  0.0},
	{-1.5,  5.0, -6.0},
	{ 0.0,  2.0, -2.0},
	{ 1.5,  5.0, -6.0},
	{ 4.0,  1.0,  0.0},
	{-4.0, -6.0,  6.0}
};

float knots[10] = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10};

SoSeparator* makeCurve() {
	SoSeparator* curveSep = new SoSeparator();
	curveSep->ref();

	SoDrawStyle* drawStyle = new SoDrawStyle;
	drawStyle->lineWidth = 3;
	curveSep->addChild(drawStyle);

	SoComplexity* complexity = new SoComplexity;
	complexity->value = 0.6;// 0-1细分复杂度

	SoPointSet* myPt = new SoPointSet;
	myPt->numPoints = 7;

	SoCoordinate3* controlPts = new SoCoordinate3;
	controlPts->point.setValues(0, 7, pts);

	SoNurbsCurve* curve = new SoNurbsCurve;
	curve->numControlPoints = 7;
	curve->knotVector.setValues(0, 10, knots);

	curveSep->addChild(complexity);
	curveSep->addChild(controlPts);
	curveSep->addChild(curve);

	drawStyle->pointSize = 5;
	curveSep->addChild(myPt);

	curveSep->unrefNoDelete();
	return curveSep;
}

int main(int, char**argv) {
	HWND myWindow = SoWin::init(argv[0]);
	if (myWindow == NULL) exit(1);

	SoSeparator* root = new SoSeparator;
	root->ref();

	SoSeparator* heart = new SoSeparator;
	SoSeparator* curveSep = makeCurve();
	SoLightModel* lmodel = new SoLightModel;
	SoBaseColor* clr = new SoBaseColor;

	lmodel->model = SoLightModel::BASE_COLOR;
	clr->rgb.setValue(SbColor(1.0f, 0.0f, 0.1f));
	heart->addChild(lmodel);
	heart->addChild(curveSep);
	root->addChild(heart);

	SoWinExaminerViewer* viewer = new SoWinExaminerViewer(myWindow);
	viewer->setSceneGraph(root);
	viewer->setBackgroundColor(SbColor(0.92f, 0.92f, 0.92f));
	viewer->setTitle("B-Spline Curve");
	viewer->show();
	viewer->show();

	SoWin::show(myWindow);
	SoWin::mainLoop();

	return 0;
}
```

**Comment by VolkerEnderlein** [comment]
Just downloaded the 64bit as well as the 32bit versions from the CI-builds section, built your program and it works as it should. So no idea what is wrong. One thing: you should not include superglu.h. This header is Coin internal only.
<img width="352" alt="BSplineHeart" src="https://user-images.githubusercontent.com/46793759/151254975-e8922a95-bcef-4988-8f27-7ff0af95e1d4.PNG">
Can you give some more information about your environment: I used Windows 10 21H2, Visual Studio 16 2019 16.11.8, on a AMD Ryzen 7 5800H, with integrated AMD Radeon graphics.

**Comment by xiaomx32** [comment]
I'm really sorry that I didn't speak clearly enough and took up so much space on the issue. 
I don't know my environment, so I made some screenshots, so I hope you get the idea.
Superglu. h is included only out of choice, including it or not is a failure.

![1](https://user-images.githubusercontent.com/78308270/151295590-48c295ea-4327-45e7-b715-2ee2ea59f2cd.png)
![2](https://user-images.githubusercontent.com/78308270/151295593-0561df85-8289-408d-a0ed-ec20115cf62a.png)
![3](https://user-images.githubusercontent.com/78308270/151295594-e29c1d8d-0e7c-49f4-af0b-9b2d8d497cd0.png)
![4](https://user-images.githubusercontent.com/78308270/151295595-616a9d5a-0ad9-4389-a845-751c27aec1a4.png)
![5](https://user-images.githubusercontent.com/78308270/151295598-49e9ce55-1cff-4af4-b851-8bfaadf0b322.png)
![6](https://user-images.githubusercontent.com/78308270/151295600-8ae345bc-20f8-4e4a-b756-2ba4fbe6a119.png)
![7](https://user-images.githubusercontent.com/78308270/151295601-19144eb7-91a9-40ba-9c1e-3278a10aec4b.png)
![9](https://user-images.githubusercontent.com/78308270/151295603-c0a3155f-ae8f-460a-869f-34f45f38e05f.png)

**Comment by VolkerEnderlein** [comment]
Thanks for the screenshots. Coin4 and the other DLLs  look rather outdated. To rule out it's those DLLs please download the latest versions of all components (Coin, SoWin, SoQt, Quarter, simage, and SimVoleon). Extract them into a new folder on your home directory and adjust the paths in your Visual Studio solution. Make sure you adapt the environment in Visual Studio to use the right folder. For that you need to add the variable PATH=<newfolder>/Coin3D/bin to the Environment box under Debugging Settings. I will later add a screenshot how to do that in an english VS.

**Comment by xiaomx32** [comment]
From the results so far, I've got the Heart curve.

But the process is puzzling.  Following your instructions, I downloaded the latest related files from CI Builds on Github and replaced the older files.  Turns out it still doesn't work (at this point, I'm compiling on x86, so the little green run button shows x86).  I saw your screenshots showing x64 and decided to give it a try.  As it turned out, after I had configured the project properties, I found another error: it compiled successfully, but failed to run on X64 platforms (that is, the small green button displayed as x64), with the error "Running program cannot start properly".  When I was disappointed, I accidentally changed the little green button to x86, and something amazing happened: the Heart curve was successfully displayed, it's really a curve.

After studying for so long, I thought I had a certain understanding of "configuring project properties". Today I was confused again.  The DLL is configured on x64 platform, why can it run successfully on x86?  

![12](https://user-images.githubusercontent.com/78308270/151337578-106bf160-9864-4336-9059-4a3cdcbda790.png)
![10](https://user-images.githubusercontent.com/78308270/151337567-ea3626a7-7d71-46e4-9ecf-91a42941b3ad.png)
![11](https://user-images.githubusercontent.com/78308270/151337576-5958213c-b104-457b-974d-510a5a67083f.png)

Finally, I really appreciate your patient guidance.  My level is not high, the foundation is very weak, but talking with you, I gained a lot. Thanks again.

**Comment by xiaomx32** [comment]
![13](https://user-images.githubusercontent.com/78308270/151341574-a5457aed-b25f-448f-8112-5fbe96e91461.png)

As you can see, I did a little testing to find out why this was happening.  Delete the DLL from the original project (which was added temporarily to rule out the code not finding the DLL) and the discovery will also run successfully.  

From this, I came to the conclusion that x64 files plus the x86 platform would make the right application .Please understand that the language may not be professional.

**Comment by VolkerEnderlein** [comment]
OK, glad you got it ro run. As you tried to build several platforms from one solution: x86 Dlls/libs can only be linked to x86 programs and x64 Dlls/libs can be linked only to x64 programs. You cannot mix them. When you said you have an existing x86 installation say Coin3D/(bin | lib | include) this is bound to a platform as Coin DLL is always named Coin4 (Coin4d for Debug). So you cannot determine from first glance what your folder contains. The error 0xc000007b you where seeing means that your program could not load the DLL as it was compiled for a different platform (e.g. you were compiling for x64 and tried to load x86 DLL). To solve the issue you need to have two separate Coin3D folders, one for x86 and one for x64. Make sure you adapt the paths in your solution properly. In the environment setting for x86 platform (Debug|Win32 and Release|Win32) you need to set the path to the x86 Coin3D folder and for the x64 platform (Debug|x64 and Release|x64)  you need to add the path to the x64 Coin3D folder. So it's not one setting for 'All Configurations` anymore. If there are still issues, check whether your program has all compile/link settings for x86 and x64 properly set. Especially the /machine:x64 setting tends not to be updated when creating a new platform based on Win32. Go through all C++ and Linker settings and look out for wrong settings. 

If that all does not help try generating your VS solutions with CMake. It's overwhelming at first but once you get acquainted to it you won't miss it anymore. Place the CMakeLists.txt file next to your example.

A simple CMakeLists.txt for your project would be:

```
cmake_minimum_required(VERSION 3.0)
project(CoinExample)
find_package(Coin REQUIRED)
find_package(SoWin REQUIRED)
add_executable(TheExample example.cpp)
target_link_libraries(TheExample PUBLIC SoWin::SoWin Coin::Coin)
```

Then for generating a x86 solution for VS 2019 you would run:

`cmake -S ExampleSourceDir -B ExampleBuildDir_x86 -G "Visual Studio 16 2019" -A Win32 -DCMAKE_PREFIX_PATH=C:\Coin3Dx86`

A x64 solution for VS 2019 could be generated by this command:

`cmake -S ExampleSourceDir -B ExampleBuildDir_x64 -G "Visual Studio 16 2019" -A x64 -DCMAKE_PREFIX_PATH=C:\Coin3Dx64`

After that you can open the generated solutions in Visual Studio or a call from the command line will build the project for you:
`cmake --build  ExampleBuildDir_x86 --target ALL_BUILD --config Release`
or 
`cmake --build  ExampleBuildDir_x64 --target ALL_BUILD --config Release`

**Comment by xiaomx32** [comment]
Since Github is fine, I probably had a little problem building the environment. This was originally caused by my own improper operation. I am deeply sorry for your disturbance these days.

**Comment by xiaomx32** [comment]
Since Github is fine, I probably had a little problem building the environment. This was originally caused by my own improper operation. I am deeply sorry for your disturbance these days.
