### ISSUE TITLE
SoGLSLShaderObject::load() reacts wrongly in case of previous OpenGL errors

### ISSUE THREAD

**Issue by YvesBoyadjian** [coin3d/coin#399]
In case there was previous OpenGL errors before the call of SoGLSLShaderObject::load(), the test at line 113 returns true, and so, the variable this->shaderHandle is set to zero, because the method wrongly thinks the shader compilation has failed.
This impeach the normal flow of the rendering, for example when using SoShadowGroup with an AMD GPU.

**Comment by YvesBoyadjian** [comment]
Suggested fix :
In file "SoGLSLShaderObject.cpp", after line 102, insert code :
SoGLSLShaderObject::didOpenGLErrorOccur("SoGLSLShaderObject::load() : previous errors");

**Comment by VolkerEnderlein** [comment]
Thanks Yves, I will apply the suggested fix. It is highly appreciated.
