### ISSUE TITLE
SoShadowGroup must use "#version 120" for better compatibility

### ISSUE THREAD

**Issue by YvesBoyadjian** [coin3d/coin#403]
Using SoShadowGroup node, I experienced problems :
- When enabling fog with an Nvidia Graphic Card
- When using MESA 3D software renderer for Windows :
[https://fdossena.com/?p=mesa/index.frag](url)

The solution is simple : One must use "#version 120" at the start of shaders.
So, in brief, in file "SoShadowGroup.ccp" : 
- At lines 1841 and 1847, replace "gen.setVersion("#version 110");" by "gen.setVersion("#version 120")";
- After line 1588, insert "gen.setVersion("#version 120")";

GLSL 1.20 is compatible with OpenGL 2.1, so it should not bring any regressions.

**Comment by VolkerEnderlein** [comment]
Thanks for contributing to Coin, Yves. As always your contribution is highly appreciated.
