### ISSUE TITLE
Disabling VBO for Intel OpenGL drivers is not relevant anymore

### ISSUE THREAD

**Issue by YvesBoyadjian** [coin3d/coin#406]
- In file [gl.cpp](https://github.com/coin3d/coin/blob/master/src/glue/gl.cpp).
- In lines 1336 to 1352.
- There is conditional code, disabling by default, VBO for Intel OpenGL driver.

=> Theses lines should be removed, as this problem is not relevant anymore.
This unnecessarily penalizes Intel graphics card users.

(Tested on Intel Graphics HD 4000)

**Comment by VolkerEnderlein** [comment]
Thanks for contributing to Coin, Yves. As always your contribution is highly appreciated.
