### ISSUE TITLE
Disabling non power of two textures for OpenGL drivers other than Nvidia is not relevant anymore

### ISSUE THREAD

**Issue by YvesBoyadjian** [coin3d/coin#407]
- In file [gl.cpp](https://github.com/coin3d/coin/blob/master/src/glue/gl.cpp).
- In method "coin_glglue_non_power_of_two_textures()".
- In lines 5264 to 5267.
- There is conditional code, to disable non power of two textures, if OpenGL vendor is not Nvidia.

=> This code should be removed, as there is no more problems with Ati and Intel OpenGL drivers for this feature.

**Comment by VolkerEnderlein** [comment]
Thanks for the patch to Coin, Yves. Your contribution is highly appreciated.
