### ISSUE TITLE
Disabling VBO in DisplayList for ATI/AMD graphic cards is not relevant anymore

### ISSUE THREAD

**Issue by YvesBoyadjian** [coin3d/coin#412]
- In file "gl.cpp".
- At line 1982.
- There is a method "glglue_check_ati_vbo_in_displaylist_bug(...)".
- This method is called at line 2525 in same file.

=> This method should be deleted, and no longer called, because the problem has been solved a long time ago by ATI/AMD.

**Comment by VolkerEnderlein** [comment]
Thanks again Yves for your issue thorough report.
