### ISSUE TITLE
SoShadowLightCache : Possible infinite loop when running on VirtualBox

### ISSUE THREAD

**Issue by YvesBoyadjian** [coin3d/coin#420]
In constructor of SoShadowLightCache, when running on CentOS 7 in VirtualBox, there can be an infinite loop in this code : 
(line 375 of SoShadowGroup.cpp)

    while (!coin_glglue_is_texture_size_legal(glue, maxsize, maxsize, 0, internalformat, format, type, TRUE)) {
      maxsize >>= 1;
    }

Instead, use this code : 

    while (!coin_glglue_is_texture_size_legal(glue, maxsize, maxsize, 0, internalformat, format, type, TRUE) && maxsize != 0 ) {
      maxsize >>= 1;
    }
    
    if(maxsize == 0) { // Can happen on CentOS 7 in VirtualBox    	
    	
        glGetIntegerv(GL_MAX_RENDERBUFFER_SIZE, &maxsize);
        glGetIntegerv(GL_MAX_TEXTURE_SIZE, &maxtexsize);
        
        if (maxtexsize < maxsize) maxsize = maxtexsize;    	
    }

**Comment by VolkerEnderlein** [comment]
Thanks Yves, for the patch, it is highly appreciated. Keep up the good work.
