### ISSUE TITLE
SoShadowGroup : Support for Intel Graphics HD 630

### ISSUE THREAD

**Issue by YvesBoyadjian** [coin3d/coin#421]
When running with an APU using Intel Graphics HD 630 ( For example, an Intel i7-7700 APU), all shaders must begin with "#version 120" in order for them to work.

So in SoShadowLightCache::createVSMProgram(), two lines must be added  : 

- After "vgen.reset(FALSE);", insert "vgen.setVersion("#version 120");"

- After "fgen.reset(FALSE);", insert "fgen.setVersion("#version 120");"

Also, in SoShadowGroupP::setVertexShader(), one line must be added : 

- After "gen.reset(FALSE);", insert "gen.setVersion("#version 120");"

**Comment by VolkerEnderlein** [comment]
Thanks for your fixes Yves. They are highly appreciated. Can you provide a PR with necessary changes/edits next time? It simplifies handling those changes a lot. Cheers Volker
