### ISSUE TITLE
CMake error

### ISSUE THREAD

**Issue by OgreTransporter** [coin3d/coin#425]
CMake 3.19.1

Call:
```
cmake -G "Visual Studio 15" -A x64 -D CMAKE_INSTALL_PREFIX:PATH=D:\Coin3D\install -D COIN_BUILD_DOCUMENTATION:BOOL=ON -D DOXYGEN_DOT_EXECUTABLE:FILEPATH=D:\dev\Tools\graphviz-2.38\bin\dot.exe -D DOXYGEN_EXECUTABLE:FILEPATH=D:\dev\Tools\doxygen-1.8.20\doxygen.exe -D BOOST_ROOT:PATH=D:\Coin3D\deps\boost\install -D Boost_INCLUDE_DIR:PATH=D:\Coin3D\deps\boost\src -D COIN_BUILD_TESTS:BOOL=OFF -D COIN_THREADSAFE:BOOL=ON D:\Coin3D\src
```

Result:
```
-- Configuring done
CMake Error: install(EXPORT "Coin" ...) includes target "Coin" more than once in the export set.
-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

Fix:
Remove last install instruction
https://github.com/coin3d/coin/blob/1baee633a8cf8ea16b8b9751d6ef88f657f7a609/src/CMakeLists.txt#L428

**Comment by VolkerEnderlein** [comment]
Thanks for making us aware of the issue. The vcpkg maintainer notified us already about build issues in simage [here](https://github.com/coin3d/simage/issues/42) and we think it's a regression in the current CMake version. See also our question in the [CMake forum](https://discourse.cmake.org/t/error-when-installing-targets-and-exports-in-3-19-1/2245) regarding this issue. It should be fixed in CMake 3.19.2

**Comment by OgreTransporter** [comment]
I am a bit astonished that the bug is known and is waiting for a new CMake version instead of putting a quick fix into the script.

**Comment by VolkerEnderlein** [comment]
Unfortunately your quick fix makes the project build succeed but breaks the provided CMake package config files. Downstream projects using those (by means of `find_package(Coin CONFIG)` or `find_package(Coin NO_MODULE)`) may not be able to link properly to Coin anymore. So I would suggest using a CMake version 3.18.x or older and wait for the proper fix in upcoming 3.19.2

**Comment by VolkerEnderlein** [comment]
I just committed the proper fix for this issue according to @rickertm 's fix for dtecta.

**Comment by OgreTransporter** [comment]
Thanks a lot! This fix works for me too.
