### ISSUE TITLE
LGTM code analysis

### ISSUE THREAD

**Issue by luzpaz** [coin3d/coin#453]
List of issues can be found at https://lgtm.com/projects/g/coin3d/coin/?mode=tree

**Comment by VolkerEnderlein** [comment]
Thanks for the static code analysis. I started to fix some of the major issues, but will need some additional time to finish the task as a lot of those issues are false positives.

**Comment by luzpaz** [comment]
Can we close ?

**Comment by luzpaz** [comment]
LGTM was sunset and consolidated in to github in 2022  
ref: https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/
