### ISSUE TITLE
SoIndexedLineSet ignores the alpha-component of "SoVertexProperty::orderedRGBA"

### ISSUE THREAD

**Issue by handegar** [coin3d/coin#462]
It seems like the `SoIndexedLineSet` ignores the alpha-component of colors in the `SoVertexProperty::orderedRGBA` array. This works as expected with a regular `SoLineSet`.

[example-files.zip](https://github.com/coin3d/coin/files/6624061/example-files.zip)

Attached is a zip with a `SoIndexedLineSet` which is not properly rendered with alpha-transparency and a `SoLineSet` which is the same data but converted to use SoLineSet instead.

I have tested using Coin3D from April 18. (the f8a82c09bb5aa62702b9ed396067a25905571c82 commit), Ubuntu 18.04.

From "glxinfo":
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel (0x8086)
    Device: Mesa Intel(R) HD Graphics 630 (KBL GT2) (0x591b)
    Version: 20.3.0
    Accelerated: yes
    Video memory: 3072MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2

**Comment by VolkerEnderlein** [comment]
@handegar Thanks for your contribution to Coin development and notifying us about the issue. A fix has been applied in PR #463.
