### ISSUE TITLE
No `debian.cmake` in `coin_build` after `make install`

### ISSUE THREAD

**Issue by glicka** [coin3d/coin#467]
I followed the instructions to install coin3d on my debian machine, but the last step to run `cpack --config debian.cmake` does not work as there is no such file in the `coin_build` folder or any subfolders.

**Comment by ggabbiani** [comment]
Hi Adam,

try this

`cd coin_build/cpack.d`
`cpack --config debian.cmake`
 
let me know.

Bye
Giampiero

**Comment by glicka** [comment]
@ggabbiani when I do `ls coin_build` the only subfolders there are:

`CMakeFiles`, `bin`, `data`, `include`, `lib`, `src`, `testsuite`. I don't see a `cpack.d` subfolder.

**Comment by ggabbiani** [comment]
ok, please check if the option COIN_USE_CPACK is set on the CMakeLists.txt file, cpack is an optional feature.

Giampiero

**Comment by glicka** [comment]
That was the issue. Thank you!
