### ISSUE TITLE
Coin warning in Sblmage::readFile():The simage library is not available, can not import any images from disk.

### ISSUE THREAD

**Issue by SunYueM** [coin3d/coin#476]
When I tried to use an image as a background image, the program warned me that I could not read the image, and a dialog box popped up as shown in the issue。
`SoImage* img = new SoImage;
img->vertAlignment = SoImage::HALF;
img->horAlignment = SoImage::CENTER;
img->filename = "D:/demo/project3/background.jpg";
sep->addChild(img);`

**Comment by VolkerEnderlein** [comment]
Coin uses the simage library as abstract interface for loading a number of file formats (JPG, PNG, TIF, ...). Depending on what platform and compiler you are using you could donwload the appropriate package from [simage Releases](https://github.com/coin3d/simage/releases). You may need to place the simage DLL next to the Coin DLL or add the simage bin directory to your PATH variable.

**Comment by SunYueM** [comment]
I did it as you said.&nbsp; I installed coin and simage by vcpkg, I don't know if this is the problem. And brought the dlls in my folder with the exe. but it didn't work.&nbsp;
Maybe I'm a green hand.😭

---Original---
From: "Volker ***@***.***&gt;
Date: Mon, Apr 4, 2022 20:57 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [coin3d/coin] Coin warning in Sblmage::readFile():The simagelibrary is not available, can not import any images from disk. (Issue #476)




 
Coin uses the simage library as abstract interface for loading a number of file formats (JPG, PNG, TIF, ...). Depending on what platform and compiler you are using you could donwload the appropriate package from simage Releases. You may need to place the simage DLL next to the Coin DLL or add the simage bin directory to your PATH variable.

**Comment by VolkerEnderlein** [comment]
Unfortunately I cannot reproduce the error. When I download [coin-latest-msvc16-x64.zip](https://github.com/coin3d/coin/releases/download/CI-builds/coin-latest-msvc16-x64.zip), [soqt-latest-msvc16-x64.zip](https://github.com/coin3d/soqt/releases/download/CI-builds/soqt-latest-msvc16-x64.zip), [simage-1.8.1-msvc16-x64.zip](https://github.com/coin3d/simage/releases/download/v1.8.1/simage-1.8.1-msvc16-x64.zip), built the soguiexamples repository  and ran the example `soguiexamples/nodekits/wavekitdemo` from exactly this source directory everything was fine. The images (jpg) are loading. The links I provided point to the latest CI build artifacts.

**Comment by VolkerEnderlein** [comment]
Did you get your issues resolved?

**Comment by xiaomx32** [comment]
Can coin3d export rendered "scenes" as images？

**Comment by VolkerEnderlein** [comment]
@xiaomx32  Yes, you can use the SoOffscreenRenderer class to render scenes to buffer or to images. See [Coin documentation](https://www.coin3d.org/Coin/html/classSoOffscreenRenderer.html) for further information.

**Comment by xiaomx32** [comment]
> @xiaomx32 Yes, you can use the SoOffscreenRenderer class to render scenes to buffer or to images. See [Coin documentation](https://www.coin3d.org/Coin/html/classSoOffscreenRenderer.html) for further information.

Thank you. I basically implemented the "print" function, just out of curiosity, why can't I print the background color of the window SoWinExaminerViewer sets. And Can I print other image formats besides JPG, such as EPS?

**Comment by VolkerEnderlein** [comment]
The background color must be explicitely set for the offscreen renderer instance with the `setBackgroundColor(const SbColor &color)` method. 
All formats supported by the simage library can be checked and output as follows:
```
	if ( viewer->offscreenRenderer().isWriteSupported(SbName(fileExtension.c_str())) )
	{
		viewer->offscreenRenderer().writeToFile(SbString(fileName.c_str()), SbName(fileExtension.c_str()));
        }
```

**Comment by xiaomx32** [comment]
![image](https://user-images.githubusercontent.com/78308270/170261677-35373047-40fd-4859-a907-f67404a75bf4.png)
Sorry, maybe I didn't make it clear: I need to export the image (preferably at a higher resolution), which is basically done now, but I found that the background color of the observer set by the SoWinExaminerViewer cannot be exported.
As shown in the image, I set the background color to white, but the exported image still has a black background (the default is black)

**Comment by veelo** [comment]
> And Can I print other image formats besides JPG, such as EPS?

For vectorized output such as PostScript have a look at https://www.coin3d.org/Coin/html/group__hardcopy.html.

**Comment by veelo** [comment]
> As shown in the image, I set the background color to white, but the exported image still has a black background (the default is black)

You'll have to inspect what the background color was set to in the examiner instance, and supply that value to the offscreen renderer instance as per Volker's instructions.

**Comment by VolkerEnderlein** [comment]
@xiaomx32 The background color of the SoWinExaminerViewer is **not** part of the scene graph. The offscreen renderer is only applied to the scene graph. That's why you need to explicitely set the color to the offscreen renderer instance.

**Comment by xiaomx32** [comment]
> @xiaomx32 The background color of the SoWinExaminerViewer is **not** part of the scene graph. The offscreen renderer is only applied to the scene graph. That's why you need to explicitely set the color to the offscreen renderer instance.

I made it, 
`offscreenRenderer.setBackgroundColor(SbColor((float)(226 / 255.0), (float)(225 / 255.0), (float)(228 / 255.0)));`
and this is the second time you've helped me. Thank you very much.

**Comment by SunYueM** [comment]
thanks for your reply.i will try again .



---Original---
From: "Volker ***@***.***&gt;
Date: Tue, Apr 5, 2022 06:19 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [coin3d/coin] Coin warning in Sblmage::readFile():The simage library is not available, can not import any images from disk. (Issue #476)




 
Unfortunately I cannot reproduce the error. When I download coin-latest-msvc16-x64.zip, soqt-latest-msvc16-x64.zip, simage-1.8.1-msvc16-x64.zip, built the soguiexamples repository  and ran the example soguiexamples/nodekits/wavekitdemo from exactly this source directory everything was fine. The images (jpg) are loading. The links I provided point to the latest CI build artifacts.
