### ISSUE TITLE
Camera is not interactive when picking

### ISSUE THREAD

**Issue by xiaodaxia-2008** [coin3d/coin#477]
If the scene graph has a SoSelection node as root, after loading some mesh, if mouse clicks inside the mesh area, I cannot manipulate the camera any more (rotating the viewer). Instead, if the mouse clicks on the empty area, the camera is interactive. 

![CoinInteractive](https://user-images.githubusercontent.com/36122917/163719984-081fa0b8-dfe8-41e7-a0da-1349df471ada.gif)

So how could I manipulate the camera while I am pressing mouse button inside an mesh area and moving the mouse (so that I can rotate the view) ?

**Comment by VolkerEnderlein** [comment]
If you are using an So@Gui@ExaminerViewer you can temporarily switch between edit and interaction modes by pressing the ALT-key. The cursor will change and you can move the camera.

**Comment by xiaodaxia-2008** [comment]
Thanks! I tried not to set the event as handled in `SoSelection`, and it seems to work for me.
