### ISSUE TITLE
is there a 4.0.1 release planned? 

### ISSUE THREAD

**Issue by looooo** [coin3d/coin#489]
Would be nice to have a new release. Is there anything planned?
https://github.com/FreeCAD/FreeCAD-Bundle/issues/133

I also need some commits which are in master but not in 4.0.0:
https://github.com/conda-forge/coin3d-feedstock/pull/23

**Comment by VolkerEnderlein** [comment]
I fully agree to have a 4.0.1 release. Still have some stuff pending regarding the pkg-config files but maybe that can wait until a 4.0.2 version.

**Comment by luzpaz** [comment]
Any more traction on this ?

**Comment by luzpaz** [comment]
@VolkerEnderlein ping

**Comment by VolkerEnderlein** [comment]
Unfortunately I've not gotten to it until now.

**Comment by lepalom** [comment]
Just FYI that Debian (and other distros) is moving from pkg-config to pkgconf.

**Comment by luzpaz** [comment]
@VolkerEnderlein any ETA in sight ?

**Comment by luzpaz** [comment]
bumpity bump

**Comment by luzpaz** [comment]
Can we have an official 4.0.1 release ?

**Comment by looooo** [comment]
@VolkerEnderlein we need a new version of coin and soqt. Do you think it's possible to create one?

**Comment by luzpaz** [comment]
What is the holdup here ?

**Comment by looooo** [comment]
> What is the holdup here ?

I don't know. Not sure what is needed to get a new release of coin3d and soqt. For pivy it is not difficult to create a new release. Bump the build number and create a release via github.

**Comment by luzpaz** [comment]
Should we fork and patch until @VolkerEnderlein et al respond ?

**Comment by looooo** [comment]
is there another contributor we can ping here who is able to create a release for coin and sort? I would not vote for forking as it creates more chaos.

**Comment by luzpaz** [comment]
I don't think there is another admin/maintainer here. All releases have been made by @VolkerEnderlein

**Comment by VolkerEnderlein** [comment]
@luzpaz @looooo Sorry for not responding to previous requests. I had some larger changes in the build system pending but that won't make it into 4.0.1 due to time limitations on my side. I'll try to provide a workable Coin 4.0.1 and SoQt 1.6.1 release over the weekend.

**Comment by VolkerEnderlein** [comment]
Done. I've done some checks but I would ask you @looooo and @luzpaz kindly to test the 4.0.1 and 1.6.1 bugfix releases.
