### ISSUE TITLE
spelling errors

### ISSUE THREAD

**Issue by lepalom** [coin3d/coin#492]
Lintian complains that:

I: libcoin80c: spelling-error-in-binary allready already [usr/lib/x86_64-linux-gnu/libCoin.so.4.0.0]
I: libcoin80c: spelling-error-in-binary convertion conversion [usr/lib/x86_64-linux-gnu/libCoin.so.4.0.0]
I: libcoin80c: spelling-error-in-binary fragement fragment [usr/lib/x86_64-linux-gnu/libCoin.so.4.0.0]
I: libcoin80c: spelling-error-in-binary statment statement [usr/lib/x86_64-linux-gnu/libCoin.so.4.0.0]
I: libcoin80c: spelling-error-in-binary touple tuple [usr/lib/x86_64-linux-gnu/libCoin.so.4.0.0]

Could you review it please?

**Comment by VolkerEnderlein** [comment]
I did a fulltext search in all sources but could not find any of the mentioned strings. Which commit did you use to build coin?

**Comment by lepalom** [comment]
4.0.0 tag that probably come [from here](https://github.com/coin3d/coin/commit/acbf0d422dbccdd80caeb68aec4060efb916f9e0).

**Comment by luzpaz** [comment]
still relevant ?

**Comment by VolkerEnderlein** [comment]
Should be fixed in 4.0.1
