### ISSUE TITLE
Not possible to compile .. non of the branches 

### ISSUE THREAD

**Issue by MariwanJ** [coin3d/coin#493]
I tried that and spent a lot of time to compile under windows VS 2019. Now way.
No cmake is provided and you cannot recret the project.

**Comment by VolkerEnderlein** [comment]
How did you built your coin3d repo clone? Did you follow the instructions in [BuildWithCMake](https://github.com/coin3d/coin/wiki/BuildWithCMake)? From your very terse description its hard to guess what went wrong. Please add all useful information to yur question.

**Comment by MariwanJ** [comment]
Ok .. thank you very much. I wasn't downloading recrusive . .. which was a mistake. 
but cmake didn't work as the page says. Anyway I used VS2019. 
but the install is not wokring as bellow :
```
Build started...
1>------ Build started: Project: INSTALL, Configuration: Debug x64 ------
1>-- Install configuration: "Debug"
1>-- Installing: C:/Program Files (x86)/Coin/include/Inventor
1>CMake Error at src/cmake_install.cmake:36 (file):
1>  file INSTALL cannot make directory "C:/Program Files
1>  (x86)/Coin/include/Inventor": No such file or directory.
1>Call Stack (most recent call first):
1>  cmake_install.cmake:39 (include)
1>
1>
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: The command "setlocal
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: "C:\Program Files\CMake\bin\cmake.exe" -DBUILD_TYPE=Debug -P cmake_install.cmake
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: :cmEnd
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: :cmErrorLevel
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: exit /b %1
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: :cmDone
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: :VCEnd" exited with code 1.
1>Done building project "INSTALL.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 4 up-to-date, 0 skipped ==========
```


Can I ask you a question that you might know the answer? 
Please I would like to inject other OpenGL library to the COIN3D .. For example SDL2 or any other library. It is a research to allow combining other libraries/program to be injected to FreeCAD which uses COIN3D. 
I hope you can answer. Thanks alot. 
Mariwan

**Comment by VolkerEnderlein** [comment]
Did you installed as administrator? Because you might need elevated privileges to install to the default install location `C:/Program Files (x86)/`. To install to a different path use the `-DCMAKE_INSTALL_PREFIX=<yourinstalldir>` on the CMake command line.

According to your question: SDL is not really an OpenGL implementation. But you can link `Coin4.lib` and the SDL framework or other OpenGL dependent libraries to **any** program/DLL (shared object) as long as the **same** OpenGL library is linked.

**Comment by MariwanJ** [comment]
Ok thanks I will try. Regarding injecting any OpenGL code into the COIN3D .. I would appreciate if you can show me a code that can draw normal opengl draiwng insde coin so I know how to use the context/buffer. 
I have little knowledge about how coin and opengl is made.. I will study the code but would appreciate if I can get a help. 
thanks.
