### ISSUE TITLE
Unnecessary environment variable checking for mutexes?

### ISSUE THREAD

**Issue by shanslow** [coin3d/coin#495]
Is there a use case for the { /* debugging */ ... } sections in cc_mutex_construct and cc_mutex_destruct to be queried per call? We noticed there was a significant lag introduced with this checking present on our release builds.

Would it be possible to either a) enclose the debugging braced check purely in a debug preprocessor check for use only in debug builds, or b) perform the environment variable check once per application run and then just query the resultant setting in each of these functions?

**Comment by VolkerEnderlein** [comment]
Nice catch. That seems to be a leftover of some mutex debugging sessions. I will change the lines in question to the proposed solution b).

**Comment by shanslow** [comment]
Thanks, much appreciated :)
