### ISSUE TITLE
Introduce debug check for access to scene graph nodes from wrong thread

### ISSUE THREAD

**Issue by Renreok** [coin3d/coin#497]
In my project we are using Coin from a multithreaded application. So it happens from time to time that developers access scene graph nodes directly from a worker thread, which usually results in hard-to-find sporadic memory corruption issues. Therefore we extended Coin with a debug check that compares the calling thread in certain situations to the thread that called SoDB::init:
- SoBase constructor
- SoBase::ref, SoBase::unref, SoBase::unrefNoDelete
- SoField::setDirty
- SoNode::notify

This captures most situations where the scene graph is modified and helps us to find such issues immediately. Although the performance impact seems to be negligible, the check can be removed completely by a compile configuration.

I uploaded the change [here](https://github.com/Renreok/coin/commit/a76e6be760dd55fe33285cd08dd99929e522b028). Note that this version is not ready to be committed into the Coin3D main repo (e.g. it's probably not a good idea to include config.h from SoDebug.h), but before I spend more effort for finding a more clean solution, I wanted to ask whether you would consider such a check as valuable for other projects. Any recommendation for a better solution would also be appreciated.

**Comment by VolkerEnderlein** [comment]
I do not see any reason not to include such debugging aids conditionally. This seems to be C++ 11. Up to now we do not force the usage of any C++ standard to compile Coin. Maybe it's time to raise the requirements.

**Comment by Renreok** [comment]
I updated my implementation to use macros in the coin-internal header coindefs.h. This is also a bit more consistent with other coin debug checks.

I also changed the CMakeLists.txt file to enable the new COIN_DEBUG_CHECK_THREAD only if the STL "thread" header file is found. Even if the header is found, the option is OFF by default, so there should not be any impact on existing projects. But yes, if anyone wants to use the option, a compiler supporting at least C++11 is required. I hope std::thread::id does not become deprecated at some point in time... but in that case one either needs to turn off the option or fix the problem.

The bigger question might actually be the use of std::exception. AFAIK, coin does not use exceptions so far. For my application I find it handy to get an exception at an access from an invalid thread, but that might not be true for other applications. Probably it's better to only call SoDebugError::post and register a custom error callback on my side. Drawback is that I need to parse the message string, but hopefully there are not sooo many errors during normal execution.

I still need to do some testing, but perhaps you could already have a look at the change and let me know your thoughts.

**Comment by VolkerEnderlein** [comment]
This looks good to me. And as the C++11 capable compilers are widely available nowadays and the option is OFF by default I've no objections against adding that to Coin. @veelo What do you think about this?

**Comment by Renreok** [comment]
Thanks for your feedback. I think I'll remove the exception, do some more testing and prepare the pull request.

**Comment by veelo** [comment]
> @veelo What do you think about this?

Sorry, I have been behind on my email feed. Great work.
