### ISSUE TITLE
COIN_INT8_T should be signed char

### ISSUE THREAD

**Issue by bogdan-neagu-lh** [coin3d/coin#506]
As defined in C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\stdint.h

Otherwise the error below:

1>C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\stdint.h(17): error C2371: 'int8_t' : redefinition; different basic types
1>          C:\Work\Qt\coin-master\build\msvc9\include\Inventor/system/inttypes.h(138) : see declaration of 'int8_t

**Comment by VolkerEnderlein** [comment]
The msvc9 build files have not been maintained for a long time. Please use the CMake workflow for building Coin. See [BuildWithCMake](https://github.com/coin3d/coin/wiki/BuildWithCMake) page on the Wiki.
