### ISSUE TITLE
Using GLSL Version >= 3.0

### ISSUE THREAD

**Issue by SherSpidey** [coin3d/coin#508]
Sorry I'm new to open inventor. I'm trying to implement a cap-clip-plane function in coin(the original SoClipPlane does not render the clip face) by using stencilbuffer just like threejs and I've already done it in OpenGL 4.6.  So, is there any chance I can do it in the coin? I try    to follow the doc but the shader chapter using glsl with "ftransform" and "gl_ModelViewMatrix". I greatly appreciate any help you can offer.

**Comment by looooo** [comment]
I can't help with this issue, but I guess freecad developers would love to see this implemented. Maybe there is a possibility to fund this. @luzpaz maybe you can help with getting the right people from freecad connected to this issue?

**Comment by luzpaz** [comment]
Maybe @wwmayer ? (sorry for the ping, but perhaps you can weigh-in ?)

**Comment by SherSpidey** [comment]
Thanks for your reply, maybe I need to generate a clipped new shape before rendering instead of implementing it in rendering pipeline.

**Comment by looooo** [comment]
@SherSpidey I played with a capping algorithm some years ago. I ended up with this python code:
https://github.com/coin3d/pivy/blob/master/examples/utils/GlClipPlane.py

but I am not sure if this can help you.

**Comment by wwmayer** [comment]
Does this help?
https://glbook.gamedev.net/GLBOOK/glbook.gamedev.net/moglgp/advclip.html

**Comment by SherSpidey** [comment]
@looooo wow, I can really look into it! thanks a lot!!!

**Comment by SherSpidey** [comment]
@wwmayer Yes! Thanks for your reply~

**Comment by looooo** [comment]
glClipPlan in coin3d:
https://github.com/coin3d/coin/blob/81dcd9f649ea34be409acbcdacdb877b88f52225/src/elements/GL/SoGLClipPlaneElement.cpp#L142L143

**Comment by SherSpidey** [comment]
Recently I decided to pick up it again by using pivy, and finally nailed it with the example code [GlClipPlane.py](https://github.com/coin3d/pivy/blob/master/examples/utils/GlClipPlane.py)! Big thanks to all of you~
![image](https://github.com/coin3d/coin/assets/43642144/60320001-cd5a-4bc4-acdf-a2fdafa66963)
