### ISSUE TITLE
Codespell report for "coin" (on fossies.org)

### ISSUE THREAD

**Issue by jschleus** [coin3d/coin#511]
Although I saw that the "coin" project already uses the "[codespell](https://github.com/codespell-project/codespell)" tool itself, as administrator of the FOSS server [fossies.org](https://fossies.org) that offers among others a feature named "[Source code misspelling reports](https://fossies.org/features.html#codespell)" I couldn't resist to setup such an analysis like for some other FOSS projects also for the development version of "coin":

&nbsp;https://fossies.org/linux/test/coin-master.tar.gz/codespell.html

That URL should redirect always to the report for the latest version identified by the short GitHub commit ID and a year-month-day string (YYMMDD) representing the according git pull date (mostly = commit date). The data are residing within a special restricted "test" folder that isn't really integrated into the standard Fossies services and should also not be accessible to search engines. The report should be available at least for some weeks and is continuously updated (currently even with a half-hourly refresh rate).

By the way, the context type of the spelling errors and typos are marked by a single character (within the sortable column "T"): The less interesting, probably not user visible ones (in "comments") are greyed, while the probably more interesting ones are black-colored. Especially interesting may be unassigned errors marked by a "?" since they may be contained in the source code itself. Some more according information is offered by a tooltip if the mouse is over the string "error context type character" above the table, over the "T" in the table header or over such a context character itself within the table. If JavaScript is enabled all table columns are sortable.

Although after a first review some obviously wrong matches ("False Positives" = FPs) are already filtered out (ignored) please inform me if you find more of them so that I can exclude them if applicable.

Ok, as expected only few misspellings and typos were found, and most of them are only in the source code comments.
By the way, the not marked word "[bieffects](https://fossies.org/linux/test/coin-master.c2eeb7f.231119.tar.gz/coin-master/configure.ac?M=1988#l_1987)" in line 1988 of the file "configure.ac" seems to be generally "unknown".

**Comment by VolkerEnderlein** [comment]
Thanks for this report, your contribution is highly appreciated. We try to fix the issues ASAP. Keep up the good Work.

**Comment by jschleus** [comment]
Great!
