### ISSUE TITLE
ABI compatiblility between 4.0.1 and 4.0.0 broken

### ISSUE THREAD

**Issue by VolkerEnderlein** [coin3d/coin#513]
It is commit cdf8bf2fd7bc1667b9c0ccb4d354cda853ff56d7 that changes the signature of functions and leads to a different ordering in the export symbols of coin 4.0.1 DLL on Windows. This was some maintenance work done by me. @WizzerWorks @looooo, @veelo, @ggabbiani, @Renreok, @kkremitzki Any idea how we should resolve this issue? Publish a bugfix release 4.0.2 ASAP without those changes, or any other suggestion? And to the distribution maintainers @podsvirov @reavertm what would you expect?

**Comment by looooo** [comment]
For me it's fine to create a new version, in the hope other distros have not yet updated to coin4.0.1. Also afaik there was an unofficial 4.0.1 version around. So a 4.0.2 version would also resolve the issue with this unofficial version.

**Comment by luzpaz** [comment]
<a href="https://repology.org/project/coin3d/versions">
    <img src="https://repology.org/badge/vertical-allrepos/coin3d.svg?columns=3&exclude_unsupported=1" alt="Packaging status"></a>

posted for convenience
