### ISSUE TITLE
src/profiler/SbProfilingData.cpp:1146: Suspicious increment ?

### ISSUE THREAD

**Issue by dcb314** [coin3d/coin#522]
C++ compiler clang says:

coin/src/profiler/SbProfilingData.cpp:1146:7: warning: variable 'idx' is incremented both in the loop header and in the loop body [-Wfor-loop-analysis]

Source code is

   ++idx;

Suggest remove this line.

**Comment by VolkerEnderlein** [comment]
I agree with you, that looks suspicious.

**Comment by VolkerEnderlein** [comment]
Thank you for your contribution to Coin development, it is highly appreciated.

**Comment by dcb314** [comment]
Thanks.

You might consider it a wise idea to compile your package
with clang from time to time and examine the warnings produced.
