### ISSUE TITLE
Any possible way to get development fixes wrapped into another minor version release? 

### ISSUE THREAD

**Issue by luzpaz** [coin3d/coin#527]
@VolkerEnderlein FreeCAD is coming up on a 1.0 Release milestone (https://blog.freecad.org/2024/08/30/1-0rc1-is-coming-next-week-lets-update-addons/). Is there any chance there can be a coin release beforehand so some of these fixes are available ?

_Originally posted by @luzpaz in https://github.com/coin3d/coin/issues/519#issuecomment-2321858309_

**Comment by VolkerEnderlein** [comment]
Sure, I was not aware of the upcoming release, thanks for notifying me/us. Do we need minor versions of other repos like SoQt, Quarter and pivy as well?

**Comment by luzpaz** [comment]
> Do we need minor versions of other repos like SoQt, Quarter and pivy as well?  

Good question! 

CC @looooo @wwmayer @rexbas @kkremitzki @adrianinsaval

**Comment by Rexbas** [comment]
For me, only the coin repo has a useful fix. But if it is not too much work and those other repos have unreleased fixes then why not make a release for them too?

**Comment by adrianinsaval** [comment]
> Sure, I was not aware of the upcoming release, thanks for notifying me/us. Do we need minor versions of other repos like SoQt, Quarter and pivy as well?

Pivy would be nice, if I'm not mistaken current stable release of pivy doesn't support qty and some distros won't ship with qt5 anymore

**Comment by looooo** [comment]
also note: while pivy works with freecad and qt6, there are still some examples which need some work to be updated to qt6.

**Comment by luzpaz** [comment]
@looooo is there an open ticket for that?

**Comment by VolkerEnderlein** [comment]
I just did the necessary steps. Tagging will be done tomorrow.

**Comment by VolkerEnderlein** [comment]
Just created the tag v4.0.3. I'll create a new minor version for SoQt, Quarter and SoWin next.

**Comment by luzpaz** [comment]
Thank you very much @VolkerEnderlein :+1:

**Comment by luzpaz** [comment]
@VolkerEnderlein one more request:
For convenience, could you add the (release notes)[https://github.com/coin3d/coin/blob/eab55e722d219cbf025f6b9ef7669e1015160728/RELNOTES#L11-L30] to the [4.0.3 tag](https://github.com/coin3d/coin/releases/tag/v4.0.3)  ?

**Comment by VolkerEnderlein** [comment]
@luzpaz I'll do, once the ABI compatiblílity is restored. Thanks

**Comment by maxwxyz** [comment]
@adrianinsaval @oursland FYI

**Comment by adrianinsaval** [comment]
> also note: while pivy works with freecad and qt6, there are still some examples which need some work to be updated to qt6.

@looooo could you give more details about what is missing? maybe people can help

**Comment by luzpaz** [comment]
Looks like a downstream packager is having an issue packaging 4.0.3 due to conflicting hashes. Something about force-pushing over a tag: https://discourse.nixos.org/t/error-hash-mismatch-in-fixed-output-derivation/52353  

It looks like they've remedied it (https://github.com/NixOS/nixpkgs/pull/342221) but perhaps next time to avoid confusion it would be better to use an avoid this approach ?

**Comment by looooo** [comment]
> > also note: while pivy works with freecad and qt6, there are still some examples which need some work to be updated to qt6.
> 
> @looooo could you give more details about what is missing? maybe people can help

Mainly I mean these examples:
https://github.com/coin3d/pivy/tree/master/examples/Mentor

Please try to run them and compare them to qt5 output.

**Comment by looooo** [comment]
I have created a release for pivy (allthough some examples are still failing for me). But I think we can try to resolve them in one of the next versions):
https://github.com/coin3d/pivy/releases/tag/0.6.9
